Bi_anlasam/Models/Ilan.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace Bi_anlasam.Models
{

    public class Ilan
    {



        [Key]
        public int IlanId { get; set; }



        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:MM/dd/yy H:mm:ss}", ApplyFormatInEditMode = true)]
        public DateTime IlanTarihi { get; set; }


        public Kullanici Kullanici { get; set; }    
        [ForeignKey("KullaniciId")]

        public int KullaniciId { get; set; }
     
        

        public Ders Ders { get; set; }  
        [ForeignKey("DersId")]

        public int DersId { get; set; }
        public Ilce Ilce { get; set; }
        [ForeignKey("IlceId")]

        public int IlceId { get; set; }

        public int Fiyat { get; set; }

        public string Baslik { get; set; }

        public string Aciklama { get; set; }
        public bool IlanDurum { get; set; }
        public ICollection<Teklif> Teklif { get; set; }


    }
}

Bi_anlasam/Controllers/IlanController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Bi_anlasam;
using Bi_anlasam.Models;

namespace Bi_anlasam.Controllers
{
    public class IlanController : Controller
    {
        private readonly BianlasamDbContext _context;

        public IlanController(BianlasamDbContext context)
        {
            _context = context;
        }

        // GET: Ilan
        public async Task<IActionResult> Index()
        {
            var bianlasamDbContext = _context.Ilan.Include(i => i.Ders.Alan).Include(i => i.Ders).Include(i => i.Kullanici);
            return View(await bianlasamDbContext.ToListAsync());
        }


        public async Task<IActionResult> Ilan()
        {


            var bianlasamDbContext = _context.Ilan.Include(i => i.Ders.Alan).Include(i => i.Ders).Include(i => i.Kullanici);

            return View(await bianlasamDbContext.ToListAsync());
        }
        public async Task<IActionResult> SecilenIlan(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var ilan = await _context.Ilan
                .Include(i => i.Ders)
                .Include(i => i.Kullanici)
                .FirstOrDefaultAsync(m => m.IlanId == id);
            if (ilan == null)
            {
                return NotFound();
            }
            TempData["IlanId"] = id;
            TempData["KullaniciAdi"] = ilan.Kullanici.TamAd;
            TempData["Ders"] = ilan.Ders.DersAd; 
            //TempData["Alan"] = ilan.Ders.Alan.AlanAd;

            TempData["Aciklama"] = ilan.Aciklama;
            //TempData["Ilce"] = ilan.Ilce.IlceAd;


            var bianlasamDbContext  = (from teklif in _context.Teklif
                                   join Kullanici in _context.Kullanici
                                   on teklif.TeklifVerenKullaniciId equals Kullanici.KullaniciId
                                   join Ilan in _context.Ilan
                                   on teklif.IlanId equals Ilan.IlanId
                                   where teklif.IlanId == id
                                   select teklif ).ToListAsync();


            //_context.Teklif.Include(i => i.Ilan).Include(i => i.TeklifVerenKullaniciId).Include(w => w.IlanId.Equals(id)).OrderBy(i=>i.TeklifId);



            return RedirectToAction("Teklifler",id);
        }



        public IActionResult Teklifler(int? id)
        {


            var bianlasamDbContext = _context.Teklif.Include(i => i.Ilan).Include(i => i.TeklifVerenKullaniciId).Include(w => w.IlanId.Equals(id));

            var teklif1 = (from teklif in _context.Teklif
                           join Kullanici in _context.Kullanici
                           on teklif.TeklifVerenKullaniciId equals Kullanici.KullaniciId
                           join Ilan in _context.Ilan
                           on teklif.IlanId equals Ilan.IlanId
                           where teklif.IlanId == id
                           select teklif).ToList();

            return View("SecilenIlan", teklif1);


            }








            //// GET: Ilan/Details/5
            //public async Task<IActionResult> Details(int? id)
            //{
            //    if (id == null)
            //    {
            //        return NotFound();
            //    }

            //    var ilan = await _context.Ilan
            //        .Include(i => i.Ders)
            //        .Include(i => i.Kullanici)
            //        .FirstOrDefaultAsync(m => m.IlanId == id);
            //    if (ilan == null)
            //    {
            //        return NotFound();
            //    }

            //    return View(ilan);
            //}

            //// GET: Ilan/Create
            //public IActionResult Create()
            //{
            //    ViewData["DersId"] = new SelectList(_context.Ders, "DersId", "DersId");
            //    ViewData["KullaniciId"] = new SelectList(_context.Kullanici, "KullaniciId", "KullaniciId");
            //    return View();
            //}

            //// POST: Ilan/Create
            //// To protect from overposting attacks, enable the specific properties you want to bind to, for 
            //// more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
            //[HttpPost]
            //[ValidateAntiForgeryToken]
            //public async Task<IActionResult> Create([Bind("IlanId,IlanTarihi,KullaniciId,DersId,Baslik,Aciklama,IlanDurum")] Ilan ilan)
            //{
            //    if (ModelState.IsValid)
            //    {
            //        _context.Add(ilan);
            //        await _context.SaveChangesAsync();
            //        return RedirectToAction(nameof(Index));
            //    }
            //    ViewData["DersId"] = new SelectList(_context.Ders, "DersId", "DersId", ilan.DersId);
            //    ViewData["KullaniciId"] = new SelectList(_context.Kullanici, "KullaniciId", "KullaniciId", ilan.KullaniciId);
            //    return View(ilan);
            //}

            //// GET: Ilan/Edit/5
            //public async Task<IActionResult> Edit(int? id)
            //{
            //    if (id == null)
            //    {
            //        return NotFound();
            //    }

            //    var ilan = await _context.Ilan.FindAsync(id);
            //    if (ilan == null)
            //    {
            //        return NotFound();
            //    }
            //    ViewData["DersId"] = new SelectList(_context.Ders, "DersId", "DersId", ilan.DersId);
            //    ViewData["KullaniciId"] = new SelectList(_context.Kullanici, "KullaniciId", "KullaniciId", ilan.KullaniciId);
            //    return View(ilan);
            //}

            //// POST: Ilan/Edit/5
            //// To protect from overposting attacks, enable the specific properties you want to bind to, for 
            //// more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
            //[HttpPost]
            //[ValidateAntiForgeryToken]
            //public async Task<IActionResult> Edit(int id, [Bind("IlanId,IlanTarihi,KullaniciId,DersId,Baslik,Aciklama,IlanDurum")] Ilan ilan)
            //{
            //    if (id != ilan.IlanId)
            //    {
            //        return NotFound();
            //    }

            //    if (ModelState.IsValid)
            //    {
            //        try
            //        {
            //            _context.Update(ilan);
            //            await _context.SaveChangesAsync();
            //        }
            //        catch (DbUpdateConcurrencyException)
            //        {
            //            if (!IlanExists(ilan.IlanId))
            //            {
            //                return NotFound();
            //            }
            //            else
            //            {
            //                throw;
            //            }
            //        }
            //        return RedirectToAction(nameof(Index));
            //    }
            //    ViewData["DersId"] = new SelectList(_context.Ders, "DersId", "DersId", ilan.DersId);
            //    ViewData["KullaniciId"] = new SelectList(_context.Kullanici, "KullaniciId", "KullaniciId", ilan.KullaniciId);
            //    return View(ilan);
            //}

            //// GET: Ilan/Delete/5
            //public async Task<IActionResult> Delete(int? id)
            //{
            //    if (id == null)
            //    {
            //        return NotFound();
            //    }

            //    var ilan = await _context.Ilan
            //        .Include(i => i.Ders)
            //        .Include(i => i.Kullanici)
            //        .FirstOrDefaultAsync(m => m.IlanId == id);
            //    if (ilan == null)
            //    {
            //        return NotFound();
            //    }

            //    return View(ilan);
            //}

            //// POST: Ilan/Delete/5
            //[HttpPost, ActionName("Delete")]
            //[ValidateAntiForgeryToken]
            //public async Task<IActionResult> DeleteConfirmed(int id)
            //{
            //    var ilan = await _context.Ilan.FindAsync(id);
            //    _context.Ilan.Remove(ilan);
            //    await _context.SaveChangesAsync();
            //    return RedirectToAction(nameof(Index));
            //}

            //private bool IlanExists(int id)
            //{
            //    return _context.Ilan.Any(e => e.IlanId == id);
            //}
        }
}

Bi_anlasam/Controllers/KayitGirisController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using System;
using System.Collections.Generic;

using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.Rendering;
using Bi_anlasam.Models;

namespace Bi_anlasam.Controllers
{
    public class KayitGirisController : Controller
    {
        private readonly BianlasamDbContext _context;

        public KayitGirisController(BianlasamDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            return View();
        }
        public IActionResult KayitOl()
        {
            return View();
        }
        public IActionResult GirisYap()
        {
            return View();
        } 
        [HttpPost]
      [ValidateAntiForgeryToken]
        public async Task<IActionResult> KayitOl([Bind("Email,Sifre,Adi,Soyadi")] Kullanici kullanici)
        {
            if (ModelState.IsValid)
            {
                _context.Add(kullanici);
                await _context.SaveChangesAsync();
                return Redirect("/Home/Index");
            }
            return Redirect("/KayitGiris/KayitOl");
        }

        [HttpPost]
        public IActionResult GirisYap(string email , string sifre)
        {
            var kullanici = _context.Kullanici.FirstOrDefault(w => w.Email.Equals(email) && w.Sifre.Equals(sifre));

            if (kullanici != null)
            {

                HttpContext.Session.SetInt32("id", kullanici.KullaniciId);
                HttpContext.Session.SetString("IsAdmin", kullanici.IsAdmin.ToString());
                return Redirect("/Home/Index");
            }



            return Redirect("GirisYap");
        }
        [HttpGet]
        public IActionResult CikisYap()
        {
            HttpContext.Session.Clear();
            return Redirect("/Home/Index");
        }

    }
}

Bi_anlasam/Controllers/ProfilController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Bi_anlasam.Models;

namespace Bi_anlasam.Controllers
{
    public class ProfilController : Controller
    {
        private  BianlasamDbContext _context;

        public ProfilController(BianlasamDbContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            List<Kullanici> profil = _context.Kullanici.ToList();

            return View(profil);
        }
        public IActionResult Create()
        {

            return View();
        }

        public async Task<IActionResult> Profil(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var profil = await _context.Kullanici
                .Include(i => i.Sehir)
                .Include(i => i.Universite)
                .FirstOrDefaultAsync(m => m.KullaniciId == id);
            if (profil == null)
            {
                return NotFound();
            }

            return View(profil);
        }



    }
}

Bi_anlasam/Views/Ilan/Ilan.cshtml
@model IEnumerable<Bi_anlasam.Models.Ilan>
@{
    ViewData["Title"] = "Ilan";
}
<div id="haftanin-ogrencileri">
    <span> Haftanın en çok ders veren öğrencileri<br></span>

    <div id="haftanin-ogrencileri-profilleri">
        <ul>
            <!--kullanicilarin fotoğraflari olacak-->
            <!---buraya gelecek olan kullanıcılar veritabanından 1-2-3-4 .haftalar olarak gelecek son 7 gün değil
            her pazartesi değişmeli-->
            <li><img src="/icons/profile_picture.png" alt=""><p>Ad Soyad</p></li>
            <li><img src="/icons/profile_picture.png" alt=""><p>Ad Soyad</p></li>
            <li><img src="/icons/profile_picture.png" alt=""><p>Ad Soyad</p></li>
            <li><img src="/icons/profile_picture.png" alt=""><p>Ad Soyad</p></li>
            <li><img src="/icons/profile_picture.png" alt=""><p>Ad Soyad</p></li>
        </ul>
        <ul>
            <li><img src="/icons/profile_picture.png" alt=""><p>Ad Soyad</p></li>
            <li><img src="/icons/profile_picture.png" alt=""><p>Ad Soyad</p></li>
            <li><img src="/icons/profile_picture.png" alt=""><p>Ad Soyad</p></li>
            <li><img src="/icons/profile_picture.png" alt=""><p>Ad Soyad</p></li>

        </ul>
    </div>

</div></center>
<div class="ilan-title">
    <a>İLANLAR</a>
</div>

<div id="ilanlar">
    <!--ARAMA BUTONU-->
    <form class="arama" style="margin:20px auto;">
        <!--aramaya girilen kelimelerde sağ sol boşluk olmama  durumuna bak   veritabanı için-->
        <input type="text" name="alan" id="" placeholder="   Alan..." onclick="this.placeholder='';">
        <input type="text" name="ders" id="" placeholder="   Ders..." onclick="this.placeholder='';">

        <button type="submit" style="height: 50px; width: 50px; top: 15px;">
            <img src="/icons/search_icon.png" style="height:20px" alt="">
        </button>
    </form>
    <br /><br /><br />

    <div id="filtreler" style=" margin-top:10px;">
        <a>     <i class="fas fa-filter" data-toggle="modal" type="button" data-target="#Modal2"> Filtre</i></a>

        <div class="modal" id="Modal2">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h4 class="modal-tittle">Filtrele</h4>

                        <form action="/" method="post">
                            <div class="modal-body">
                                <nav id="filtre-ilan">
                                    <!--FİLTRELER-->


                                    <form id="filtre">
                                        <br>
                                        <!--Fiyat-->
                                        <!--proje bitince buraya alanların zorluk seviyesine göre kıstas belirlenecek-->
                                        <nav id="filtre-fiyat">
                                            Fiyat:
                                            <br>
                                            <br>
                                            <input type="text" name="ders" id="" value="  max" onclick="this.value='';">  -
                                            <input type="text" name="ders" id="" value="  max" onclick="this.value='';">
                                            <br><br>
                                        </nav>

                                        <!--Alan:-->
                                        <nav id="filtre-alan">
                                            Alan:
                                            <br>
                                            <br>
                                            <input type="text" name="ders" id="" value="  Mimarlık,Ekonomi..." onclick="this.value='';">

                                            <br><br>
                                        </nav>

                                        <!--Ders:-->
                                        <nav id="filtre-ders">
                                            Ders:
                                            <br>
                                            <br>
                                            <input type="text" name="ders" id="" value="  Anatomi,İntegral..." onclick="this.value='';">


                                        </nav>   <!--Konum-->
                                        <!--buradaki şehirler veritabanından gelecek-->
                                        <nav id="filtre-konum">
                                            Konum:
                                            <br><br>

                                            <select>
                                                <option selected>İl</option>
                                                <option>Trabzon</option>
                                                <option>Sivas</option>
                                                <option>Konya</option>
                                                <option>İstanbul</option>
                                            </select> /

                                            <select>
                                                <option selected>İlçe</option>
                                                <option>Trabzon</option>
                                                <option>Sivas</option>
                                                <option>Konya</option>
                                                <option>İstanbul</option>
                                            </select>


                                            <br><br>
                                        </nav>

                                        <br><br>
                                        <!--Şuanki Filtreler:-->
                                        <nav id="filtre-uygula-temizle">

                                            <button type="reset">Temizle</button><br>

                                        </nav>
                                        <nav id="filtre-uygula-temizle">
                                            <button type="submit">Uygula</button>
                                        </nav>
                                    </form>

                            </div>

                        </form>
                    </div>
                </div>
            </div>
        </div>
        <a>  <i class="fas fa-sort-amount-down">Önce en düşük fiyat</i>  </a>

        <a> <i class="fas fa-sort-amount-up"> Önce en yüksek fiyat  </i> </a>

        <a>  <i class="fas fa-sort-amount-up"> Önce en yeni  </i>     </a>

        <a>  <i class="fas fa-sort-amount-down"> Önce en eski </i>    </a>

    </div>
    <div id="ilanlar-kapsayici">


        @foreach (var item in Model)
        {


            <div id="ilan-icerik">
                <!--kullanıcının profil fotoğrafı -->
                <nav  asp-action="ProfileGit" asp-route-id="@item.Kullanici.KullaniciId" id="profil-pp"><img src="/icons/profile_picture.png" alt=""></nav>
                <!--ilan veren kullanıcının adı soyadı ve diğer ilan bilgileri-->
                <nav id="ilan-bilgileri">
                    <!--ilan bilgilerini kapsayan div-->

                    <div id="ilan">
                        <!--1.satır-->
                        <nav style="width:40%;">
                            <a asp-controller="Profil"  asp-action="Profil" asp-route-id="@item.Kullanici.KullaniciId">
                                <span>
                                    @Html.DisplayFor(modelItem => item.Kullanici.TamAd)
                                </span>
                            </a>
                        </nav><!--1.satırın içindeki 1.sütun-->

                        <nav style="float:right;  display: flex; flex-direction:row;  width:70%;">
                            <!--1.satırın içindeki 2.sütun-->
                            <span style="width:500px;">
                                @Html.DisplayFor(modelItem => item.Ders.Alan.AlanAd)--
                                @Html.DisplayFor(modelItem => item.Ders.DersAd)

                            </span>
                            <a  class="teklif-buton" asp-action="SecilenIlan" asp-route-id="@item.IlanId">   
                            <i type="button" class="fas fa-money-bill-alt"> @Html.DisplayFor(modelItem => item.Fiyat)</i> 
                            <br />   <br />Teklif ver</a>


                        </nav>
                    </div>

                    <div id="konum">
                        <!--2.satır-->
                        <!--ilan veren kullanıcının ders verebileceği konum alanı-->
                        <i id="konum">
                            <img src="/icons/location.png" alt="">
                            @Html.DisplayFor(modelItem => item.Ilce.IlceAd)
                        </i>

                    </div>
                </nav>

            </div>
        }

    </div>
    <!--- ilanların alt kısmına sayfa numaraları üst kısmına sıralama açılır menüsü gelecek-->
    <!-- İLANLARIN GELECEĞİ YER-->
    </nav><!---yukarı git eklenebilir-->
</div>

Bi_anlasam/Views/Ilan/SecilenIlan.cshtml
@using Microsoft.AspNetCore.Identity;
@inject Microsoft.AspNetCore.Http.IHttpContextAccessor HttpContextAccessor
@using Microsoft.AspNetCore.Http;



@{
    ViewData["Title"] = "SecilenIlan";
}
<div id="secilen-ilan">
    <div id="hemen-ilan-ver">
        <img src="/image/hemen-kendi-ilanini-ver.png">
        <br>
        <!--İlan oluşturmaya yönlendirir-->

        @if (HttpContextAccessor.HttpContext.Session.GetInt32("id") == null)
        {<button id="secilen-ilan-ders-al" asp-area="" asp-controller="KayitGiris" asp-action="Index">Ders Al</button>

        }
        else
        {<button id="secilen-ilan-ders-al" data-toggle="modal" type="button" data-target="#Modal1">Ders Al</button>
            @Html.Partial("_DersAlPopup")
        }

    </div>


    <nav id="ana-ilan">
        <div id="ana-ilan-satir-1">
            <nav id="satir-1-sutun-1">
                <!--Profil fotoğrafı kısmı-->
                <img src="/icons/profile_picture.png" style="width: 35%; margin-top: 15%; align-self: center;">
            </nav>


            <nav id="satir-1-sutun-2">
                <!--Ad soyad ve puan  kısmı-->
                <a>@TempData["KullaniciAdi"]</a>
                <br>
                <i style="font-size:0.7rem; float: left;">40   değerlendirme</i>
            </nav>

            <nav id="satir-1-sutun-3">
                <!--İlan bilgileri kısmı-->
                <a style="font-size:1.2rem; ">
                    @TempData["Ders"]
                    <br />
                    @TempData["Alan"]
                </a>
                <i style="float: right; margin-right:20px; font-size:0.7rem;">5 saat önce</i>
                <br>
                <br>
                <!--Açıklama kısmı-->
                <a style="font-size: 0.9em;">
                    @TempData["Aciklama"]

                </a>
            </nav>
        </div>

        <div id="ana-ilan-satir-2">
            <!-- konum ve fiyat kısmı-->
            <i style="float: left;">
                <img src="/icons/location.png" style="width:7%; ">  <br />
                @TempData["Ilce"]  /  @TempData["Sehir"]


            </i>
            <nav style="float:right;">
                <a style="float:right; margin-right:7%; width:100% ;font-size:0.75em ">
                    <i type="button" class="fas fa-money-bill-alt"> </i>  @TempData["Fiyat"] ₺/sa
                </a>
                <br>


                <a class="teklif-buton" data-toggle="modal" data-target="#Modal3">   Teklif ver</a>
            </nav>
            <div class="modal" id="Modal3">
                <div class="modal-dialog" style="width: 20%; display: flex; ">
                    <div class="modal-content">
                        <div class="modal-header">
                            <form action="/" method="post">
                                <div class="modal-body">
                                    <div class="title">
                                        <h6>Teklif Giriniz </h6> <br />

                                    </div>
                                    <div class="content">
                                        <input type="text" style=" margin: 10px 10px auto 10%;">  <p>

                                            <button class="teklif-buton" type="submit" name="ders" id="filtre-uygula-temizle" style=" margin: 10%; width: 90%;">
                                                <i class="fas fa-money-bill-alt" type="button"></i> Teklif ver
                                            </button>
                                        </p>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </nav>
    @*@{Html.RenderAction("_Teklifler"); }*@


    @model List<Teklif>

    @foreach (var item in Model)
    {
        if (Model != null)
        {
            <nav id="teklifler">
                <!--- tekliflerin tümünü kapsayan -->
                <center>
                    <!--her teklif altalta gelecek-->
                    <nav id="teklif">

                        <nav id="satir-1-sutun-1">
                            <!--Profil fotoğrafı kısmı-->
                            <img src="/icons/profile_picture.png" style="float: right; width:40%; margin-top:20px;">
                        </nav>

                        <nav id="satir-1-sutun-2">
                            <!--Ad soyad ve puan  kısmı-->
                            <a></a> &nbsp&nbsp&nbsp<i style="font-size:0.7rem;  ">40   değerlendirme</i>
                            <br>Üniversite  / Bölüm
                        </nav>

                        <nav id="satir-1-sutun-3">
                            <!--Teklif Kısmı-->
                            <input class="teklif-buton" type="button" value="10 TL/sa" style="width:50%; height:30%; margin:20% 20% auto auto;">
                        </nav>


                    </nav>
                </center>
            </nav>}
        else
        { <nav id="teklifler">
                <a>Teklif yok.</a>
            </nav>

        }
    }


    <br>
    <br>

    </center>
    <br>
    <br>

Bi_anlasam/Views/Ilan/_Teklifler.cshtml
@model List<Teklif>

@foreach (var item in Model)
{
    if (Model != null)
    {
        <nav id="teklifler">
            <!--- tekliflerin tümünü kapsayan -->
            <center>
                <!--her teklif altalta gelecek-->
                <nav id="teklif">

                    <nav id="satir-1-sutun-1">
                        <!--Profil fotoğrafı kısmı-->
                        <img src="/icons/profile_picture.png" style="float: right; width:40%; margin-top:20px;">
                    </nav>

                    <nav id="satir-1-sutun-2">
                        <!--Ad soyad ve puan  kısmı-->
                        <a>Ad Soyad</a> &nbsp&nbsp&nbsp<i style="font-size:0.7rem;  ">40   değerlendirme</i>
                        <br>Üniversite  / Bölüm
                    </nav>

                    <nav id="satir-1-sutun-3">
                        <!--Teklif Kısmı-->
                        <input class="teklif-buton" type="button" value="10 TL/sa" style="width:50%; height:30%; margin:20% 20% auto auto;">
                    </nav>


                </nav>
            </center>
        </nav>}
    else
    { <nav id="teklifler">
            <a>Teklif yok.</a>
        </nav>

    }
}