Bi_anlasam/Controllers/HomeController.cs
using Bi_anlasam.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace Bi_anlasam.Controllers
{
    public class HomeController : Controller
    {
        

        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }




        public IActionResult Index()
        {
            return View();
        }


        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Bi_anlasam/Controllers/IlanController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Bi_anlasam;
using Bi_anlasam.Models;

namespace Bi_anlasam.Controllers
{
    public class IlanController : Controller
    {
        private readonly BianlasamDbContext _context;

        public IlanController(BianlasamDbContext context)
        {
            _context = context;
        }

        // GET: Ilan
        public async Task<IActionResult> Index()
        {
            var bianlasamDbContext = _context.Ilan.Include(i => i.Ders.Alan).Include(i => i.Ders).Include(i => i.Kullanici);
            return View(await bianlasamDbContext.ToListAsync());
        }


        public async Task<IActionResult> Ilan()
        {


            var bianlasamDbContext = _context.Ilan.Include(i => i.Ders.Alan).Include(i => i.Ders).Include(i => i.Kullanici);

            return View(await bianlasamDbContext.ToListAsync());
        }
        public async Task<IActionResult> SecilenIlan(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var ilan = await _context.Ilan
                .Include(i => i.Ders)
                .Include(i => i.Kullanici)
                .FirstOrDefaultAsync(m => m.IlanId == id);
            if (ilan == null)
            {
                return NotFound();
            }
            TempData["IlanId"] = id;
            TempData["KullaniciAdi"] = ilan.Kullanici.TamAd;
            TempData["Ders"] = ilan.Ders.DersAd; 
            //TempData["Alan"] = ilan.Ders.Alan.AlanAd;

            TempData["Aciklama"] = ilan.Aciklama;
            //TempData["Ilce"] = ilan.Ilce.IlceAd;


            var bianlasamDbContext  = (from teklif in _context.Teklif
                                   join Kullanici in _context.Kullanici
                                   on teklif.TeklifVerenKullaniciId equals Kullanici.KullaniciId
                                   join Ilan in _context.Ilan
                                   on teklif.IlanId equals Ilan.IlanId
                                   where teklif.IlanId == id
                                   select teklif ).ToListAsync();


            //_context.Teklif.Include(i => i.Ilan).Include(i => i.TeklifVerenKullaniciId).Include(w => w.IlanId.Equals(id)).OrderBy(i=>i.TeklifId);



            return RedirectToAction("Teklifler",id);
        }



        public IActionResult Teklifler(int? id)
        {


            var bianlasamDbContext = _context.Teklif.Include(i => i.Ilan).Include(i => i.TeklifVerenKullaniciId).Include(w => w.IlanId.Equals(id));

            var teklif1 = (from teklif in _context.Teklif
                           join Kullanici in _context.Kullanici
                           on teklif.TeklifVerenKullaniciId equals Kullanici.KullaniciId
                           join Ilan in _context.Ilan
                           on teklif.IlanId equals Ilan.IlanId
                           where teklif.IlanId == id
                           select teklif).ToList();

            return View("SecilenIlan", teklif1);


            }








            //// GET: Ilan/Details/5
            //public async Task<IActionResult> Details(int? id)
            //{
            //    if (id == null)
            //    {
            //        return NotFound();
            //    }

            //    var ilan = await _context.Ilan
            //        .Include(i => i.Ders)
            //        .Include(i => i.Kullanici)
            //        .FirstOrDefaultAsync(m => m.IlanId == id);
            //    if (ilan == null)
            //    {
            //        return NotFound();
            //    }

            //    return View(ilan);
            //}

            //// GET: Ilan/Create
            //public IActionResult Create()
            //{
            //    ViewData["DersId"] = new SelectList(_context.Ders, "DersId", "DersId");
            //    ViewData["KullaniciId"] = new SelectList(_context.Kullanici, "KullaniciId", "KullaniciId");
            //    return View();
            //}

            //// POST: Ilan/Create
            //// To protect from overposting attacks, enable the specific properties you want to bind to, for 
            //// more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
            //[HttpPost]
            //[ValidateAntiForgeryToken]
            //public async Task<IActionResult> Create([Bind("IlanId,IlanTarihi,KullaniciId,DersId,Baslik,Aciklama,IlanDurum")] Ilan ilan)
            //{
            //    if (ModelState.IsValid)
            //    {
            //        _context.Add(ilan);
            //        await _context.SaveChangesAsync();
            //        return RedirectToAction(nameof(Index));
            //    }
            //    ViewData["DersId"] = new SelectList(_context.Ders, "DersId", "DersId", ilan.DersId);
            //    ViewData["KullaniciId"] = new SelectList(_context.Kullanici, "KullaniciId", "KullaniciId", ilan.KullaniciId);
            //    return View(ilan);
            //}

            //// GET: Ilan/Edit/5
            //public async Task<IActionResult> Edit(int? id)
            //{
            //    if (id == null)
            //    {
            //        return NotFound();
            //    }

            //    var ilan = await _context.Ilan.FindAsync(id);
            //    if (ilan == null)
            //    {
            //        return NotFound();
            //    }
            //    ViewData["DersId"] = new SelectList(_context.Ders, "DersId", "DersId", ilan.DersId);
            //    ViewData["KullaniciId"] = new SelectList(_context.Kullanici, "KullaniciId", "KullaniciId", ilan.KullaniciId);
            //    return View(ilan);
            //}

            //// POST: Ilan/Edit/5
            //// To protect from overposting attacks, enable the specific properties you want to bind to, for 
            //// more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
            //[HttpPost]
            //[ValidateAntiForgeryToken]
            //public async Task<IActionResult> Edit(int id, [Bind("IlanId,IlanTarihi,KullaniciId,DersId,Baslik,Aciklama,IlanDurum")] Ilan ilan)
            //{
            //    if (id != ilan.IlanId)
            //    {
            //        return NotFound();
            //    }

            //    if (ModelState.IsValid)
            //    {
            //        try
            //        {
            //            _context.Update(ilan);
            //            await _context.SaveChangesAsync();
            //        }
            //        catch (DbUpdateConcurrencyException)
            //        {
            //            if (!IlanExists(ilan.IlanId))
            //            {
            //                return NotFound();
            //            }
            //            else
            //            {
            //                throw;
            //            }
            //        }
            //        return RedirectToAction(nameof(Index));
            //    }
            //    ViewData["DersId"] = new SelectList(_context.Ders, "DersId", "DersId", ilan.DersId);
            //    ViewData["KullaniciId"] = new SelectList(_context.Kullanici, "KullaniciId", "KullaniciId", ilan.KullaniciId);
            //    return View(ilan);
            //}

            //// GET: Ilan/Delete/5
            //public async Task<IActionResult> Delete(int? id)
            //{
            //    if (id == null)
            //    {
            //        return NotFound();
            //    }

            //    var ilan = await _context.Ilan
            //        .Include(i => i.Ders)
            //        .Include(i => i.Kullanici)
            //        .FirstOrDefaultAsync(m => m.IlanId == id);
            //    if (ilan == null)
            //    {
            //        return NotFound();
            //    }

            //    return View(ilan);
            //}

            //// POST: Ilan/Delete/5
            //[HttpPost, ActionName("Delete")]
            //[ValidateAntiForgeryToken]
            //public async Task<IActionResult> DeleteConfirmed(int id)
            //{
            //    var ilan = await _context.Ilan.FindAsync(id);
            //    _context.Ilan.Remove(ilan);
            //    await _context.SaveChangesAsync();
            //    return RedirectToAction(nameof(Index));
            //}

            //private bool IlanExists(int id)
            //{
            //    return _context.Ilan.Any(e => e.IlanId == id);
            //}
        }
}

Bi_anlasam/Controllers/KayitGirisController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using System;
using System.Collections.Generic;

using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.Rendering;
using Bi_anlasam.Models;

namespace Bi_anlasam.Controllers
{
    public class KayitGirisController : Controller
    {
        private readonly BianlasamDbContext _context;

        public KayitGirisController(BianlasamDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            return View();
        }
        public IActionResult KayitOl()
        {
            return View();
        }
        public IActionResult GirisYap()
        {
            return View();
        } 
        [HttpPost]
      [ValidateAntiForgeryToken]
        public async Task<IActionResult> KayitOl([Bind("Email,Sifre,Adi,Soyadi")] Kullanici kullanici)
        {
            if (ModelState.IsValid)
            {
                _context.Add(kullanici);
                await _context.SaveChangesAsync();
                return Redirect("/Home/Index");
            }
            return Redirect("/KayitGiris/KayitOl");
        }

        [HttpPost]
        public IActionResult GirisYap(string email , string sifre)
        {
            var kullanici = _context.Kullanici.FirstOrDefault(w => w.Email.Equals(email) && w.Sifre.Equals(sifre));

            if (kullanici != null)
            {

                HttpContext.Session.SetInt32("id", kullanici.KullaniciId);
                HttpContext.Session.SetString("IsAdmin", kullanici.IsAdmin.ToString());
                return Redirect("/Home/Index");
            }



            return Redirect("GirisYap");
        }
        [HttpGet]
        public IActionResult CikisYap()
        {
            HttpContext.Session.Clear();
            return Redirect("/Home/Index");
        }

    }
}

Bi_anlasam/Views/Home/Index.cshtml
@{
@using Microsoft.AspNetCore.Identity;

@inject Microsoft.AspNetCore.Http.IHttpContextAccessor HttpContextAccessor
@using Microsoft.AspNetCore.Http;

ViewData["Title"] = "Anasayfa";
}
<div id="header-bg"></div>


<div class="header">

    <span>Anlamadığın Her Konuda  Arkadaşların Yanında</span>

    <div class="dersal-ver"  aria-label="Basic example">

        <button  asp-area="" asp-controller="Ilan" asp-action="Ilan" type="button" class ="button btn btn-secondary dersal-ver">Ders Ver</button>
        @if (HttpContextAccessor.HttpContext.Session.GetInt32("id") == null)
        {<button class="button btn btn-secondary dersal-ver" asp-area="" asp-controller="KayitGiris" asp-action="KayitOl">Ders Al</button>

        }
        else
        { <button class="button btn btn-secondary dersal-ver" data-toggle="modal" type="button" data-target="#Modal1">Ders Al</button>
            @Html.Partial("_DersAlPopup")
        }


    </div>


</div>



<p id="orta_yazi">Yüzlerce Alandan  İlanlar Senin İçin Burada</p>

<!--Arama Kısmı-->
<form  asp-action="IlanAra" asp-controller="Ilan"  method="post" class="arama" style="text-align:center; padding:15px;">
    <input   type="text" name="alan"  value="   Alan..." onclick="this.value=''; color: black;">
    @*@foreach (var alan in Model)
        {
            <h2>@Html.DisplayFor(modelItem=> alan.AlanAd)  </h2> <br />


        }*@

    <input type="text" name="ders"  value="   Ders..." onclick="this.value='';">
    <button type="submit" style="height: 50px; width: 50px; top: 15px;">
        <img src="/icons/search_icon.png" style="height:20px" alt="">
    </button>
</form>



<!--Tanıtım için var olan alanların iconları filtrelenmiş ilanlara yönlendirir-->

<section id="bolumlerin-iconlari">
    <ul>

        <li asp-area=""><img src="/60-60/bilgisayar.png" alt=""><p>Bilgisayar</p></li>
        <li><img src="/60-60/beslenme.png" alt=""><p>Beslenme</p></li>
        <li><img src="/60-60/biyoloji.png" alt=""><p>Biyoloji</p></li>
        <li><img src="/60-60/elektrik.png" alt=""><p>Elektrik</p></li>
        <li><img src="/60-60/finans.png" alt=""><p>Finans</p></li>
        <li><img src="/60-60/fizik.png" alt=""><p>Fizik</p></li>
        <li><img src="/60-60/hukuk.png" alt=""><p>Hukuk</p></li>

        <li><img src="/60-60/ingilizce.png" alt=""><p>Yabancı Dil</p></li>
        <li><img src="/60-60/kimya.png" alt=""><p>Kimya</p></li>
        <li><img src="/60-60/makine (2).png" alt=""><p>Makine</p></li>
        <li><img src="/60-60/psikoloji.png" alt=""><p>Psikoloji</p></li>
        <li><img src="/60-60/saglik.png" alt=""><p>Bilgisayar</p></li>
        <li><img src="/60-60/tarih.png" alt=""><p>Tarih</p></li>
        <li><img src="/60-60/elektrik.png" alt=""><p>Elektrik</p></li>
    </ul>
</section>

<!-- görsellik için -->
<div id="calisan-ogrenciler">
    <img src="/image/calisan-ogrenciler.png" alt="">
</div>