Bi_anlasam/Controllers/IlanController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Bi_anlasam;
using Bi_anlasam.Models;

namespace Bi_anlasam.Controllers
{
    public class IlanController : Controller
    {
        private readonly BianlasamDbContext _context;

        public IlanController(BianlasamDbContext context)
        {
            _context = context;
        }

        // GET: Ilan
        public async Task<IActionResult> Index()
        {
            var bianlasamDbContext = _context.Ilan.Include(i => i.Ders.Alan).Include(i => i.Ders).Include(i => i.Kullanici);
            return View(await bianlasamDbContext.ToListAsync());
        }


        public async Task<IActionResult> Ilan()
        {


            var bianlasamDbContext = _context.Ilan.Include(i => i.Ders.Alan).Include(i => i.Ders).Include(i => i.Kullanici);

            return View(await bianlasamDbContext.ToListAsync());
        }
        public async Task<IActionResult> SecilenIlan(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var ilan = await _context.Ilan
                .Include(i => i.Ders)
                .Include(i => i.Kullanici)
                .FirstOrDefaultAsync(m => m.IlanId == id);
            if (ilan == null)
            {
                return NotFound();
            }
            TempData["IlanId"] = id;
            TempData["KullaniciAdi"] = ilan.Kullanici.TamAd;
            TempData["Ders"] = ilan.Ders.DersAd; 
            //TempData["Alan"] = ilan.Ders.Alan.AlanAd;

            TempData["Aciklama"] = ilan.Aciklama;
            //TempData["Ilce"] = ilan.Ilce.IlceAd;


            var bianlasamDbContext  = (from teklif in _context.Teklif
                                   join Kullanici in _context.Kullanici
                                   on teklif.TeklifVerenKullaniciId equals Kullanici.KullaniciId
                                   join Ilan in _context.Ilan
                                   on teklif.IlanId equals Ilan.IlanId
                                   where teklif.IlanId == id
                                   select teklif ).ToListAsync();


            //_context.Teklif.Include(i => i.Ilan).Include(i => i.TeklifVerenKullaniciId).Include(w => w.IlanId.Equals(id)).OrderBy(i=>i.TeklifId);



            return RedirectToAction("Teklifler",id);
        }



        public IActionResult Teklifler(int? id)
        {


            var bianlasamDbContext = _context.Teklif.Include(i => i.Ilan).Include(i => i.TeklifVerenKullaniciId).Include(w => w.IlanId.Equals(id));

            var teklif1 = (from teklif in _context.Teklif
                           join Kullanici in _context.Kullanici
                           on teklif.TeklifVerenKullaniciId equals Kullanici.KullaniciId
                           join Ilan in _context.Ilan
                           on teklif.IlanId equals Ilan.IlanId
                           where teklif.IlanId == id
                           select teklif).ToList();

            return View("SecilenIlan", teklif1);


            }








            //// GET: Ilan/Details/5
            //public async Task<IActionResult> Details(int? id)
            //{
            //    if (id == null)
            //    {
            //        return NotFound();
            //    }

            //    var ilan = await _context.Ilan
            //        .Include(i => i.Ders)
            //        .Include(i => i.Kullanici)
            //        .FirstOrDefaultAsync(m => m.IlanId == id);
            //    if (ilan == null)
            //    {
            //        return NotFound();
            //    }

            //    return View(ilan);
            //}

            //// GET: Ilan/Create
            //public IActionResult Create()
            //{
            //    ViewData["DersId"] = new SelectList(_context.Ders, "DersId", "DersId");
            //    ViewData["KullaniciId"] = new SelectList(_context.Kullanici, "KullaniciId", "KullaniciId");
            //    return View();
            //}

            //// POST: Ilan/Create
            //// To protect from overposting attacks, enable the specific properties you want to bind to, for 
            //// more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
            //[HttpPost]
            //[ValidateAntiForgeryToken]
            //public async Task<IActionResult> Create([Bind("IlanId,IlanTarihi,KullaniciId,DersId,Baslik,Aciklama,IlanDurum")] Ilan ilan)
            //{
            //    if (ModelState.IsValid)
            //    {
            //        _context.Add(ilan);
            //        await _context.SaveChangesAsync();
            //        return RedirectToAction(nameof(Index));
            //    }
            //    ViewData["DersId"] = new SelectList(_context.Ders, "DersId", "DersId", ilan.DersId);
            //    ViewData["KullaniciId"] = new SelectList(_context.Kullanici, "KullaniciId", "KullaniciId", ilan.KullaniciId);
            //    return View(ilan);
            //}

            //// GET: Ilan/Edit/5
            //public async Task<IActionResult> Edit(int? id)
            //{
            //    if (id == null)
            //    {
            //        return NotFound();
            //    }

            //    var ilan = await _context.Ilan.FindAsync(id);
            //    if (ilan == null)
            //    {
            //        return NotFound();
            //    }
            //    ViewData["DersId"] = new SelectList(_context.Ders, "DersId", "DersId", ilan.DersId);
            //    ViewData["KullaniciId"] = new SelectList(_context.Kullanici, "KullaniciId", "KullaniciId", ilan.KullaniciId);
            //    return View(ilan);
            //}

            //// POST: Ilan/Edit/5
            //// To protect from overposting attacks, enable the specific properties you want to bind to, for 
            //// more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
            //[HttpPost]
            //[ValidateAntiForgeryToken]
            //public async Task<IActionResult> Edit(int id, [Bind("IlanId,IlanTarihi,KullaniciId,DersId,Baslik,Aciklama,IlanDurum")] Ilan ilan)
            //{
            //    if (id != ilan.IlanId)
            //    {
            //        return NotFound();
            //    }

            //    if (ModelState.IsValid)
            //    {
            //        try
            //        {
            //            _context.Update(ilan);
            //            await _context.SaveChangesAsync();
            //        }
            //        catch (DbUpdateConcurrencyException)
            //        {
            //            if (!IlanExists(ilan.IlanId))
            //            {
            //                return NotFound();
            //            }
            //            else
            //            {
            //                throw;
            //            }
            //        }
            //        return RedirectToAction(nameof(Index));
            //    }
            //    ViewData["DersId"] = new SelectList(_context.Ders, "DersId", "DersId", ilan.DersId);
            //    ViewData["KullaniciId"] = new SelectList(_context.Kullanici, "KullaniciId", "KullaniciId", ilan.KullaniciId);
            //    return View(ilan);
            //}

            //// GET: Ilan/Delete/5
            //public async Task<IActionResult> Delete(int? id)
            //{
            //    if (id == null)
            //    {
            //        return NotFound();
            //    }

            //    var ilan = await _context.Ilan
            //        .Include(i => i.Ders)
            //        .Include(i => i.Kullanici)
            //        .FirstOrDefaultAsync(m => m.IlanId == id);
            //    if (ilan == null)
            //    {
            //        return NotFound();
            //    }

            //    return View(ilan);
            //}

            //// POST: Ilan/Delete/5
            //[HttpPost, ActionName("Delete")]
            //[ValidateAntiForgeryToken]
            //public async Task<IActionResult> DeleteConfirmed(int id)
            //{
            //    var ilan = await _context.Ilan.FindAsync(id);
            //    _context.Ilan.Remove(ilan);
            //    await _context.SaveChangesAsync();
            //    return RedirectToAction(nameof(Index));
            //}

            //private bool IlanExists(int id)
            //{
            //    return _context.Ilan.Any(e => e.IlanId == id);
            //}
        }
}

Bi_anlasam/Controllers/KurumsalController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Bi_anlasam.Controllers
{
    public class KurumsalController : Controller
    {
    

        public IActionResult GizlilikPolitikasi()
        {
            return View();
        }
        public IActionResult Hakkimizda()
        {
            return View();
        }
        public IActionResult Iletisim()
        {
            return View();
        }
        public IActionResult KullaniciSozlesmesi()
        {
            return View();
        }
        public IActionResult ToplulukKurallari()
        {
            return View();
        }

    }
}

Bi_anlasam/Views/Shared/_DersAlPopup.cshtml
<div class="modal" id="Modal1">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-tittle">İLAN OLUŞTUR</h4>

                <form asp-action="IlanOlustur" asp-controller="Ilan" >
                    <div class="modal-body">
                        <div class="content">
                            <ul>
                                <li>
                                    <input type="text" placeholder="Ders">
                                </li>
                                <li>
                                    <input type="text" placeholder="Konu">
                                </li>
                            </ul>
                            <ul>
                                <li>
                                    <select class="form-control" id="il" name="il" autocomplete="off">
                                        <option value="0">İl Seçiniz</option>
                                    </select>

                                </li>
                                <li>
                                    <select class="form-control" id="ilce" name="ilce" autocomplete="off">
                                        <option value="0">İlçe Seçiniz</option>
                                    </select>
                                </li>
                            </ul>
                            <ul>
                                <li>
                                    <input type="text" placeholder="Min">&nbsp; - &nbsp;
                                </li>
                                <li>
                                    <input type="text" placeholder="Max">
                                </li>
                            </ul>
                            <section><textarea name="aciklama" id="" cols="50" rows="5" placeholder="Açıklama"></textarea></section>
                            <ul>
                                <li>
                                    <button type="submit">Yayınla</button>
                                </li>
                            </ul>

                        </div>
                    </div>

                </form>
            </div>
        </div>
    </div>
</div>

Bi_anlasam/Views/Shared/_Layout.cshtml
@{@using Microsoft.AspNetCore.Identity;

@using Microsoft.AspNetCore.Http;

@inject Microsoft.AspNetCore.Http.IHttpContextAccessor HttpContextAccessor ;
@using Microsoft.AspNetCore.Mvc;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <title>@ViewData["Title"] - Bi'anlasam</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
    <script src="JsLocalSearch.js" type="text/javascript"></script>

    <script src="https://code.jquery.com/jquery-1.12.4.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />

    <link rel="shortcut icon" href="/icons/logo1.png" type="image/x-icon">
    <script src="https://kit.fontawesome.com/5b756dfa76.js" crossorigin="anonymous"></script>

    <link href="normalize.css" rel="stylesheet" type="text/css" />
    <meta http-equiv="Content-Type" content="text/html;" />
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,user-scalable=no, initial-scale=1.0">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img src="/image/logo.png" alt="" class="logo"></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Anasayfa</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Ilan" asp-action="Ilan">İlanlar</a>
                        </li>

                        @if (HttpContextAccessor.HttpContext.Session.GetString("IsAdmin") =="True")
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Admin</a>
                            </li>
                        }
                    </ul>
                </div>

                <partial name="_LoginPartial" />

            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container" style="font-size:0.75em">
            &copy; 2021 - Bianlasam -
            <a asp-area="" asp-controller="Kurumsal" asp-action="Hakkimizda">Hakkımızda  |  </a>
            <a asp-area="" asp-controller="Kurumsal" asp-action="KullaniciSozlesmesi">Kullanıcı Sözleşmesi  |  </a>
            <a asp-area="" asp-controller="Kurumsal" asp-action="Gizlilikpolitikasi">Gizlilik Politikası  |  </a>
            <a asp-area="" asp-controller="Kurumsal" asp-action="Toplulukkurallari">Topluluk Kuralları  |  </a>
            <a asp-area="" asp-controller="Kurumsal" asp-action="Iletisim">İletişim</a>


        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>